[server]
hostname = "localhost"
# offset  = 10

[user_store]
type = "read_only_ldap"

[keystore.primary]
file_name = "repository/resources/security/wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "repository/resources/security/client-truststore.jks"
password = "wso2carbon"
alias = "symmetric.key.value"
algorithm = "AES"

## This is to avoid issue of adding a new phase to axis2 via deployment.toml removing all existing phases.
## Now user just need to add/remove phase to/from relevant place from the below list

#====== InFlow phase ==========#
[[transport.phase_order]]
phase_type = "InFlow"

[[transport.phase_order.phases]]
phase_name = "MsgInObservation"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.synapse.transport.passthru.util.TraceMessageBuilderDispatchHandler"
handler_name = "TraceMessageBuilderDispatchHandler"

[[transport.phase_order.phases]]
phase_name = "Validation"

[[transport.phase_order.phases]]
phase_name = "Transport"

[[transport.phase_order.phases.handlers]]
handler_class = "org.wso2.micro.integrator.core.handlers.IntegratorStatefulHandler"
handler_name = "IntegratorStatefulHandler"
handler_order_phase = "Transport"

[[transport.phase_order.phases.handlers.handler_handlers]]
handler_name="JSONMessageHandler"
handler_class="org.apache.axis2.json.gson.JSONMessageHandler"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.synapse.transport.passthru.util.RelaySecuirtyMessageBuilderDispatchandler"
handler_name = "RelaySecuirtyMessageBuilderDispatchandler"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.SOAPActionBasedDispatcher"
handler_name = "SOAPActionBasedDispatcher"
handler_order_phase = "Transport"

[[transport.phase_order.phases]]
phase_name = "Addressing"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.AddressingBasedDispatcher"
handler_name = "AddressingBasedDispatcher"
handler_order_phase = "Addressing"

[[transport.phase_order.phases]]
phase_name = "Security"

[[transport.phase_order.phases]]
phase_name = "PreDispatch"

[[transport.phase_order.phases]]
phase_name = "Dispatch"
phase_class = "org.apache.axis2.engine.DispatchPhase"
[[transport.phase_order.phases.handlers]]
handler_class = "org.wso2.micro.integrator.core.handlers.IntegratorStatefulHandler"
handler_name = "IntegratorStatefulHandler"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.json.gson.JSONMessageHandler"
handler_name = "JSONMessageHandler"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.SOAPActionBasedDispatcher"
handler_name = "SOAPActionBasedDispatcher"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.RequestURIOperationDispatcher"
handler_name = "RequestURIOperationDispatcher"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.SOAPMessageBodyBasedDispatcher"
handler_name = "SOAPMessageBodyBasedDispatcher"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.HTTPLocationBasedDispatcher"
handler_name = "HTTPLocationBasedDispatcher"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.synapse.core.axis2.SynapseDispatcher"
handler_name = "SynapseDispatcher"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.synapse.core.axis2.SynapseMustUnderstandHandler"
handler_name = "SynapseMustUnderstandHandler"

[[transport.phase_order.phases]]
phase_name = "RMPhase"

[[transport.phase_order.phases]]
phase_name = "OpPhase"

[[transport.phase_order.phases]]
phase_name = "AuthPhase"

[[transport.phase_order.phases]]
phase_name = "MUPhase"

[[transport.phase_order.phases]]
phase_name = "OperationInPhase"

#====== OutFlow phase ==========#
[[transport.phase_order]]
phase_type = "OutFlow"

[[transport.phase_order.phases]]
phase_name = "UEPPhase"

[[transport.phase_order.phases]]
phase_name = "RMPhase"

[[transport.phase_order.phases]]
phase_name = "MUPhase"

[[transport.phase_order.phases]]
phase_name = "OpPhase"

[[transport.phase_order.phases]]
phase_name = "OperationOutPhase"

[[transport.phase_order.phases]]
phase_name = "PolicyDetermination"

[[transport.phase_order.phases]]
phase_name = "PTSecurityOutPhase"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.synapse.transport.passthru.util.RelaySecuirtyMessageBuilderDispatchandler"
handler_name = "RelaySecuirtyMessageBuilderDispatchandler"

[[transport.phase_order.phases]]
phase_name = "MessageOut"

[[transport.phase_order.phases]]
phase_name = "Security"

[[transport.phase_order.phases]]
phase_name = "MsgOutObservation"

#====== InFaultFlow phase ==========#
[[transport.phase_order]]
phase_type = "InFaultFlow"

[[transport.phase_order.phases]]
phase_name = "MsgInObservation"

[[transport.phase_order.phases]]
phase_name = "Validation"

[[transport.phase_order.phases]]
phase_name = "Transport"

[[transport.phase_order.phases.handlers]]
handler_class = "org.wso2.micro.integrator.core.handlers.IntegratorStatefulHandler"
handler_name = "IntegratorStatefulHandler"
handler_order_phase = "Transport"

# THIS SECTION WAS ADDED
[[transport.phase_order.phases.handlers.handler_handlers]]
handler_name="JSONMessageHandlerCarbon"
handler_class="org.apache.axis2.json.gson.JSONMessageHandler"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.SOAPActionBasedDispatcher"
handler_name = "SOAPActionBasedDispatcher"
handler_order_phase = "Transport"

[[transport.phase_order.phases]]
phase_name = "Addressing"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.AddressingBasedDispatcher"
handler_name = "AddressingBasedDispatcher"
handler_order_phase = "Addressing"

[[transport.phase_order.phases]]
phase_name = "Security"

[[transport.phase_order.phases]]
phase_name = "PreDispatch"

[[transport.phase_order.phases]]
phase_name = "Dispatch"
phase_class = "org.apache.axis2.engine.DispatchPhase"

[[transport.phase_order.phases.handlers]]
handler_class = "org.wso2.micro.integrator.core.handlers.IntegratorStatefulHandler"
handler_name = "IntegratorStatefulHandler"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.SOAPActionBasedDispatcher"
handler_name = "SOAPActionBasedDispatcher"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.RequestURIOperationDispatcher"
handler_name = "RequestURIOperationDispatcher"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.SOAPMessageBodyBasedDispatcher"
handler_name = "SOAPMessageBodyBasedDispatcher"

[[transport.phase_order.phases.handlers]]
handler_class = "org.apache.axis2.dispatchers.HTTPLocationBasedDispatcher"
handler_name = "HTTPLocationBasedDispatcher"

[[transport.phase_order.phases]]
phase_name = "RMPhase"

[[transport.phase_order.phases]]
phase_name = "OpPhase"

[[transport.phase_order.phases]]
phase_name = "MUPhase"

[[transport.phase_order.phases]]
phase_name = "OperationInFaultPhase"

#====== OutFaultFlow phase ==========#
[[transport.phase_order]]
phase_type = "OutFaultFlow"

[[transport.phase_order.phases]]
phase_name = "UEPPhase"

[[transport.phase_order.phases]]
phase_name = "RMPhase"

[[transport.phase_order.phases]]
phase_name = "MUPhase"

[[transport.phase_order.phases]]
phase_name = "OperationOutFaultPhase"

[[transport.phase_order.phases]]
phase_name = "PolicyDetermination"

[[transport.phase_order.phases]]
phase_name = "MessageOut"

[[transport.phase_order.phases]]
phase_name = "Security"

[[transport.phase_order.phases]]
phase_name = "Transport"

[[transport.phase_order.phases]]
phase_name = "MsgOutObservation"

## Following are set of example configs. Please refer docs for complete set of configurations.

# [transport.http]
# socket_timeout = 180000   # timeout in milliseconds
# disable_connection_keepalive = false
# connection_timeout = 90000 # in milliseconds

# [transport.jms]
# sender_enable = true
# listener_enable = true

# [[transport.jms.sender]]
# name = "myQueueSender"
# parameter.initial_naming_factory = "org.apache.activemq.jndi.ActiveMQInitialContextFactory"
# parameter.provider_url = "tcp://localhost:61616"
# parameter.connection_factory_name = "QueueConnectionFactory"
# parameter.connection_factory_type = "queue"
# parameter.cache_level = "producer"


#[[transport.jms.listener]]
# name = "myQueueConnectionFactory"
# parameter.initial_naming_factory = "org.apache.activemq.jndi.ActiveMQInitialContextFactory"
# parameter.provider_url = "tcp://localhost:61616"
# parameter.connection_factory_name = "QueueConnectionFactory"
# parameter.connection_factory_type = "queue"

# [transport.jndi.connection_factories]
# 'connectionfactory.QueueConnectionFactory' = "amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'"
# 'connectionfactory.TopicConnectionFactory' = "amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'"

# [transport.jndi.queue]
# jndiNameOfQueue = "physicalNameOfQueue"

# [transport.jndi.topic]
# jndiNameOfTopic = "physicalNameOfTopic"

# [transport.rabbitmq]
# sender_enable = true
# listener_enable = true

# [[transport.rabbitmq.sender]]
# name = "AMQPConnectionFactory"
# parameter.hostname = "localhost"
# parameter.port = 5672
# parameter.username = "guest"
# parameter.password = "guest"

# [[transport.rabbitmq.listener]]
# name = "AMQPConnectionFactory"
# parameter.hostname = "localhost"
# parameter.port = 5672
# parameter.username = "guest"
# parameter.password = "guest"

# [system.parameter]
# 'key' = "value"

# [[datasource]]
# id = "WSO2CarbonDB"  # "WSO2_COORDINATION_DB"
# url = "jdbc:mysql://localhost:3306/integratordb"
# username = "root"
# password = "root"
# driver = "com.mysql.jdbc.Driver"

# [management_api]
# protocols = "http"

# [[internal_apis.users]]
# user.name = "user-1"
# user.password = "pwd-1"

# [transaction_counter]
# enable = true
# data_source = "WSO2CarbonDB"
# update_interval = 2

# [mediation]
# synapse.global_timeout_interval = "120000"  # interval in milliseconds

# [secrets]
# secret_key = "[secret value]"

# [[service_catalog]]
# apim_host = "https://localhost:9443"
# enable = true
# username = "admin"
# password = "admin"

# [dashboard_config]
# dashboard_url = "https://localhost:9743/dashboard/api/"
