name: All Tests ( openjdk8 )

on: [push]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -fae

  MacOS:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -fae

  windows:

    runs-on: windows-latest

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -fae
